export default {
  users: [
    {
      name: 'admin',
      email: 'admin@example.com',
      password: 'test1234',
      isAdmin: true,
    },
    {
      name: 'hassan',
      email: 'hassan@example.com',
      password: 'test1234',
    },
  ],
  products: [
    {
      // _id: '111111111111111111111111',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 60,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description:
        'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nostrum, necessitatibus.',
    },
    {
      // _id: '2',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing.',
    },
    {
      // _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Optio laborum cum excepturi autem.',
    },
    {
      // _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
      description: 'consectetur, adipisicing elit. Nostrum, necessitatibus.',
    },
    {
      // _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
      description:
        'nihil reprehenderit quidem, illo magni obcaecati. Quae ad totam vitae distinctio dicta',
    },
    {
      // _id: '6',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
      description: 'Lorem ipsum dolor sit amet elit. Nostrum, necessitatibus.',
    },
  ],
};
